import Head from 'next/head'
import Header from '../components/Header'
import Banner from '../components/Banner'
import GetAllPosts from '../components/api_calls/GetAllPosts'
import { Props } from '../components/Types'


const Home = (props: Props) => {
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium Service App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='text-red-500'>{props.posts[0].content}</h1>
      <Header/>
      <Banner/>
    </div>
  )
}
export default Home
export const getServerSideProps = () => {
  return GetAllPosts()
}
